import type { StaffMemberDTO } from "@/hooks/use-staff-list";

export type StaffMember = StaffMemberDTO & {
  name: string;
  caseloadCurrent: number;
  caseloadMax: number;
};

export const dummyStaffMembers: StaffMember[] = [
  {
    id: "dummy-1",
    userId: "user-1",
    firstName: "James",
    lastName: "Wilson",
    name: "James Wilson",
    email: "james@example.com",
    orgEmail: "james@firm.com",
    phone: "+1 (555) 111-1111",
    role: "attorney",
    status: "active",
    jobTitle: "Senior Attorney",
    startDate: "2024-01-15",
    maxCaseload: 10,
    caseloadCurrent: 6,
    caseloadMax: 10,
    practiceAreas: ["Immigration", "Family law"],
    team: "Immigration Team A",
    createdAt: "2024-01-15T00:00:00Z",
    updatedAt: "2024-06-01T00:00:00Z",
  },
  {
    id: "dummy-2",
    userId: "user-2",
    firstName: "Sarah",
    lastName: "Mensah",
    name: "Sarah Mensah",
    email: "sarah@example.com",
    orgEmail: "sarah@firm.com",
    phone: "+1 (555) 222-2222",
    role: "paralegal",
    status: "active",
    jobTitle: "Paralegal",
    startDate: "2024-03-01",
    maxCaseload: 7,
    caseloadCurrent: 4,
    caseloadMax: 7,
    practiceAreas: ["Business", "Employment"],
    team: "Immigration Team A",
    createdAt: "2024-03-01T00:00:00Z",
    updatedAt: "2024-06-01T00:00:00Z",
  },
  {
    id: "dummy-3",
    userId: "user-3",
    firstName: "Mark",
    lastName: "Chen",
    name: "Mark Chen",
    email: "mark@example.com",
    orgEmail: "mark@firm.com",
    phone: "+1 (555) 333-3333",
    role: "admin",
    status: "on_leave",
    jobTitle: "Office Administrator",
    startDate: "2023-06-01",
    maxCaseload: 5,
    caseloadCurrent: 0,
    caseloadMax: 5,
    practiceAreas: [],
    team: "",
    createdAt: "2023-06-01T00:00:00Z",
    updatedAt: "2024-05-15T00:00:00Z",
  },
  {
    id: "dummy-4",
    userId: "user-4",
    firstName: "Lisa",
    lastName: "Park",
    name: "Lisa Park",
    email: "lisa@example.com",
    orgEmail: "lisa@firm.com",
    phone: "+1 (555) 444-4444",
    role: "attorney",
    status: "recertify_required",
    jobTitle: "Associate Attorney",
    startDate: "2024-02-01",
    maxCaseload: 8,
    caseloadCurrent: 7,
    caseloadMax: 8,
    practiceAreas: ["Real estate", "Estate planning"],
    team: "Family & Estate Team",
    createdAt: "2024-02-01T00:00:00Z",
    updatedAt: "2024-06-01T00:00:00Z",
  },
  {
    id: "dummy-5",
    userId: null,
    firstName: "David",
    lastName: "Khan",
    name: "David Khan",
    email: "david.khan@example.com",
    orgEmail: null,
    phone: "+1 (555) 555-5555",
    role: "attorney",
    status: "pending_invitation",
    jobTitle: null,
    startDate: null,
    maxCaseload: 7,
    caseloadCurrent: 0,
    caseloadMax: 7,
    practiceAreas: ["Criminal defense"],
    team: "",
    createdAt: "2024-06-10T00:00:00Z",
    updatedAt: "2024-06-10T00:00:00Z",
  },
  {
    id: "dummy-6",
    userId: "user-6",
    firstName: "Emily",
    lastName: "Rodriguez",
    name: "Emily Rodriguez",
    email: "emily@example.com",
    orgEmail: "emily@firm.com",
    phone: "+1 (555) 666-6666",
    role: "paralegal",
    status: "active",
    jobTitle: "Senior Paralegal",
    startDate: "2023-09-01",
    maxCaseload: 6,
    caseloadCurrent: 5,
    caseloadMax: 6,
    practiceAreas: ["Immigration"],
    team: "Immigration Team A",
    createdAt: "2023-09-01T00:00:00Z",
    updatedAt: "2024-06-01T00:00:00Z",
  },
  {
    id: "dummy-7",
    userId: "user-7",
    firstName: "Michael",
    lastName: "Thompson",
    name: "Michael Thompson",
    email: "michael@example.com",
    orgEmail: "michael@firm.com",
    phone: "+1 (555) 777-7777",
    role: "attorney",
    status: "active",
    jobTitle: "Partner",
    startDate: "2022-01-10",
    maxCaseload: 12,
    caseloadCurrent: 9,
    caseloadMax: 12,
    practiceAreas: ["Business", "Employment", "Real estate"],
    team: "",
    createdAt: "2022-01-10T00:00:00Z",
    updatedAt: "2024-06-01T00:00:00Z",
  },
  {
    id: "dummy-8",
    userId: "user-8",
    firstName: "Jessica",
    lastName: "Patel",
    name: "Jessica Patel",
    email: "jessica@example.com",
    orgEmail: "jessica@firm.com",
    phone: "+1 (555) 888-8888",
    role: "attorney",
    status: "active",
    jobTitle: "Associate Attorney",
    startDate: "2024-04-01",
    maxCaseload: 8,
    caseloadCurrent: 3,
    caseloadMax: 8,
    practiceAreas: ["Family law", "Estate planning"],
    team: "Family & Estate Team",
    createdAt: "2024-04-01T00:00:00Z",
    updatedAt: "2024-06-01T00:00:00Z",
  },
  {
    id: "dummy-9",
    userId: "user-9",
    firstName: "Robert",
    lastName: "Okafor",
    name: "Robert Okafor",
    email: "robert@example.com",
    orgEmail: "robert@firm.com",
    phone: "+1 (555) 999-9999",
    role: "paralegal",
    status: "active",
    jobTitle: "Paralegal",
    startDate: "2024-05-15",
    maxCaseload: 7,
    caseloadCurrent: 2,
    caseloadMax: 7,
    practiceAreas: ["Criminal defense", "Personal injury"],
    team: "",
    createdAt: "2024-05-15T00:00:00Z",
    updatedAt: "2024-06-01T00:00:00Z",
  },
  {
    id: "dummy-10",
    userId: "user-10",
    firstName: "Amanda",
    lastName: "Foster",
    name: "Amanda Foster",
    email: "amanda@example.com",
    orgEmail: "amanda@firm.com",
    phone: "+1 (555) 101-0101",
    role: "admin",
    status: "active",
    jobTitle: "Practice Manager",
    startDate: "2023-03-20",
    maxCaseload: 3,
    caseloadCurrent: 0,
    caseloadMax: 3,
    practiceAreas: [],
    team: "",
    createdAt: "2023-03-20T00:00:00Z",
    updatedAt: "2024-06-01T00:00:00Z",
  },
  {
    id: "dummy-11",
    userId: "user-11",
    firstName: "Thomas",
    lastName: "Mueller",
    name: "Thomas Mueller",
    email: "thomas@example.com",
    orgEmail: "thomas@firm.com",
    phone: "+1 (555) 111-0101",
    role: "attorney",
    status: "on_leave",
    jobTitle: "Senior Attorney",
    startDate: "2021-08-01",
    maxCaseload: 10,
    caseloadCurrent: 0,
    caseloadMax: 10,
    practiceAreas: ["Immigration", "Business"],
    team: "Immigration Team A",
    createdAt: "2021-08-01T00:00:00Z",
    updatedAt: "2024-06-01T00:00:00Z",
  },
  {
    id: "dummy-12",
    userId: "user-12",
    firstName: "Sophie",
    lastName: "Lam",
    name: "Sophie Lam",
    email: "sophie@example.com",
    orgEmail: "sophie@firm.com",
    phone: "+1 (555) 222-0202",
    role: "attorney",
    status: "recertify_required",
    jobTitle: "Associate Attorney",
    startDate: "2024-01-01",
    maxCaseload: 8,
    caseloadCurrent: 8,
    caseloadMax: 8,
    practiceAreas: ["Family law"],
    team: "Family & Estate Team",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-06-01T00:00:00Z",
  },
  {
    id: "dummy-13",
    userId: null,
    firstName: "Daniel",
    lastName: "Carter",
    name: "Daniel Carter",
    email: "daniel.carter@example.com",
    orgEmail: null,
    phone: "+1 (555) 333-0303",
    role: "paralegal",
    status: "pending_invitation",
    jobTitle: null,
    startDate: null,
    maxCaseload: 7,
    caseloadCurrent: 0,
    caseloadMax: 7,
    practiceAreas: ["Real estate"],
    team: "",
    createdAt: "2024-06-12T00:00:00Z",
    updatedAt: "2024-06-12T00:00:00Z",
  },
  {
    id: "dummy-14",
    userId: "user-14",
    firstName: "Olivia",
    lastName: "Martinez",
    name: "Olivia Martinez",
    email: "olivia@example.com",
    orgEmail: "olivia@firm.com",
    phone: "+1 (555) 444-0404",
    role: "attorney",
    status: "active",
    jobTitle: "Of Counsel",
    startDate: "2023-11-01",
    maxCaseload: 9,
    caseloadCurrent: 4,
    caseloadMax: 9,
    practiceAreas: ["Employment", "Business", "Personal injury"],
    team: "",
    createdAt: "2023-11-01T00:00:00Z",
    updatedAt: "2024-06-01T00:00:00Z",
  },
  {
    id: "dummy-15",
    userId: "user-15",
    firstName: "William",
    lastName: "Brown",
    name: "William Brown",
    email: "william@example.com",
    orgEmail: "william@firm.com",
    phone: "+1 (555) 555-0505",
    role: "paralegal",
    status: "active",
    jobTitle: "Junior Paralegal",
    startDate: "2024-06-01",
    maxCaseload: 5,
    caseloadCurrent: 1,
    caseloadMax: 5,
    practiceAreas: ["Estate planning", "Family law"],
    team: "Family & Estate Team",
    createdAt: "2024-06-01T00:00:00Z",
    updatedAt: "2024-06-01T00:00:00Z",
  },
];

export function toStaffMember(dto: StaffMemberDTO): StaffMember {
  return {
    ...dto,
    name: `${dto.firstName} ${dto.lastName}`,
    caseloadCurrent: 0,
    caseloadMax: dto.maxCaseload ?? 7,
  };
}

export function getStatusBadgeStyles(status: string) {
  switch (status) {
    case "active":
      return { bg: "rgba(29, 158, 117, 0.15)", color: "#1D9E75" };
    case "recertify_required":
      return { bg: "rgba(232, 166, 53, 0.15)", color: "#E8A635" };
    case "on_leave":
      return { bg: "rgba(180, 178, 169, 0.2)", color: "fg.muted" };
    case "pending_invitation":
      return { bg: "rgba(83, 74, 183, 0.15)", color: "#8B83EC" };
    default:
      return { bg: "bg.muted", color: "fg" };
  }
}

export function getStatusLabel(status: string): string {
  switch (status) {
    case "active":
      return "Active";
    case "recertify_required":
      return "Recertify required";
    case "on_leave":
      return "On leave";
    case "pending_invitation":
      return "Pending invitation";
    default:
      return status;
  }
}

export function getProgressColor(current: number, max: number) {
  const ratio = current / max;
  if (ratio >= 0.75) return "red.500";
  if (ratio >= 0.5) return "orange.400";
  return "teal.400";
}

export const tabsConfig = [
  { value: "accounts", label: "Staff accounts" },
  { value: "teams", label: "Teams" },
  { value: "certifications", label: "Certifications" },
  { value: "performance", label: "Performance" },
  { value: "time-tracking", label: "Time tracking" },
  { value: "leave", label: "Leave" },
  { value: "invitations", label: "Invitations" },
];
