import { Box, Button, HStack, Stack, Text } from "@chakra-ui/react";

import { BrandButton } from "@/components/ui/intake-ui";
import type { ImportPlan } from "@/api/platform";

/**
 * What importing this blank would do to the catalogue.
 *
 * ─── This is a review step, and it replaces one that was real ───────────────
 *
 * A form's catalogue used to be a JSON file, generated by a script and then
 * *committed* — so somebody read the diff before it reached anyone's matter.
 * The file is gone, but the reason for the diff has not: these rows decide what
 * prints on a statutory form for every firm in the deployment.
 *
 * So the upload describes the change and this is where it is read. Numbers
 * first, because four of the five are usually zero and the shape of the change
 * is the thing to take in; then the two lists that are worth naming rather than
 * counting, because each entry is a decision somebody has to look at.
 */
export function ImportPlanSummary({
  plan,
  isPending,
  onImport,
  onDismiss,
}: {
  plan: ImportPlan;
  isPending: boolean;
  onImport: () => void;
  onDismiss: () => void;
}) {
  return (
    <Box
      borderWidth="1px"
      borderColor="border"
      borderRadius="md"
      bg="bg.subtle"
      p={3}
    >
      <Stack gap={2.5}>
        <Text fontSize="12px" fontWeight="600">
          {plan.fields} fields, printing into {plan.boxes} boxes
        </Text>

        <Stack gap={1}>
          <Line
            n={plan.added.length}
            one="field is new"
            many="fields are new"
          />
          <Line
            n={plan.changed.length}
            one="field has a new wording, section or type"
            many="fields have a new wording, section or type"
          />
          <Line
            n={plan.carriedForward.length}
            one="box keeps the answer it printed on the last version"
            many="boxes keep the answers they printed on the last version"
          />
          <Line
            n={plan.deferredToMapping.length}
            one="box keeps what you set by hand"
            many="boxes keep what you set by hand"
          />
        </Stack>

        {plan.removed.length > 0 && (
          /*
            A field the catalogue holds that this blank has no box for. Named
            rather than counted, and reported rather than deleted: it may be a
            curated datum waiting to be pointed at a box, and removing one
            silently is how a datum stops printing with nothing saying so.
          */
          <Box>
            <Text fontSize="11px" fontWeight="600" color="fg.muted">
              {plan.removed.length} field
              {plan.removed.length === 1 ? " has" : "s have"} no box on this PDF —
              kept, not deleted
            </Text>
            <Text
              fontSize="11px"
              color="fg.muted"
              fontFamily="mono"
              mt={0.5}
              lineHeight="16px"
              wordBreak="break-all"
            >
              {plan.removed.slice(0, 12).join(", ")}
              {plan.removed.length > 12 && ` … and ${plan.removed.length - 12} more`}
            </Text>
          </Box>
        )}

        <HStack gap={2} pt={0.5}>
          <BrandButton size="xs" h="28px" fontSize="12px" loading={isPending} onClick={onImport}>
            Save the fields
          </BrandButton>
          <Button
            size="xs"
            variant="ghost"
            fontSize="12px"
            h="28px"
            onClick={onDismiss}
          >
            Not now
          </Button>
        </HStack>

        <Text fontSize="11px" color="fg.muted" lineHeight="16px">
          The PDF is saved either way. Nothing changes for any firm until you
          save the fields, and nothing already filled in on a matter is
          affected.
        </Text>
      </Stack>
    </Box>
  );
}

/** One count, in a sentence, and nothing at all when it is zero. */
function Line({ n, one, many }: { n: number; one: string; many: string }) {
  if (n === 0) return null;
  return (
    <Text fontSize="12px" color="fg.muted">
      <Text as="span" fontWeight="600" color="fg">
        {n}
      </Text>{" "}
      {n === 1 ? one : many}
    </Text>
  );
}
