/**
 * The mappings a person has already made by hand, as evidence.
 *
 * Generated from the backend, joining each
 * `src/db/seeds/data/<code>.field-sources.json` to the box name its datum was
 * pointed at in `<code>.form-fields.json`. Checked in rather than read across
 * repos, because it is the *record of a decision* — 252 judgements about which
 * box holds which datum — and a ranking is only worth measuring against
 * judgements somebody actually stands behind.
 *
 * Regenerate when a form is wired or rewired. The numbers pinned in
 * `rank-field-keys.test.ts` are read off exactly these rows.
 */

/** `[form code, the tail of the box name, the datum a person chose]`. */
export const WIRED_BY_HAND: ReadonlyArray<readonly [string, string, string]> = [
  ["I-130", "AlienNumber", "petitioner.alien_number"],
  ["I-130", "FamilyName", "petitioner.family_name"],
  ["I-130", "GivenName", "petitioner.given_name"],
  ["I-130", "MiddleName", "petitioner.middle_name"],
  ["I-130", "CountryofBirth", "petitioner.country_of_birth"],
  ["I-130", "DateofBirth", "petitioner.date_of_birth"],
  ["I-130", "SSN", "petitioner.ssn"],
  ["I-130", "DateOfMarriage", "marriage.date"],
  ["I-130", "DaytimePhoneNumber", "petitioner.daytime_phone"],
  ["I-130", "Email", "petitioner.email"],
  ["I-130", "AlienNumber", "beneficiary.alien_number"],
  ["I-130", "USCISOnlineActNumber", "beneficiary.uscis_online_account_number"],
  ["I-130", "SSN", "beneficiary.ssn"],
  ["I-130", "FamilyName", "beneficiary.family_name"],
  ["I-130", "GivenName", "beneficiary.given_name"],
  ["I-130", "MiddleName", "beneficiary.middle_name"],
  ["I-130", "CityTownOfBirth", "beneficiary.city_of_birth"],
  ["I-130", "CountryOfBirth", "beneficiary.country_of_birth"],
  ["I-130", "DateOfBirth", "beneficiary.date_of_birth"],
  ["I-130", "Female", "beneficiary.sex"],
  ["I-130", "DaytimePhoneNumber", "beneficiary.daytime_phone"],
  ["I-130", "EmailAddress", "beneficiary.email"],
  ["I-130", "DateOfMarriage", "marriage.date"],
  ["I-130", "CityTown", "marriage.city"],
  ["I-130", "State", "marriage.state"],
  ["I-130", "Country", "marriage.country"],
  ["I-130", "ClassOfAdmission", "beneficiary.status_at_last_arrival"],
  ["I-130", "ArrivalDeparture", "beneficiary.i94_number"],
  ["I-130", "DateOfArrival", "beneficiary.date_of_last_arrival"],
  ["I-130", "PassportNumber", "beneficiary.passport_number"],
  ["I-130", "InCareofName", "petitioner.mailing_address.in_care_of"],
  ["I-130", "StreetNumberName", "petitioner.mailing_address.street"],
  ["I-130", "AptSteFlrNumber", "petitioner.mailing_address.unit"],
  ["I-130", "CityOrTown", "petitioner.mailing_address.city"],
  ["I-130", "State", "petitioner.mailing_address.state"],
  ["I-130", "ZipCode", "petitioner.mailing_address.zip"],
  ["I-130", "Province", "petitioner.mailing_address.province"],
  ["I-130", "PostalCode", "petitioner.mailing_address.postal_code"],
  ["I-130", "Country", "petitioner.mailing_address.country"],
  ["I-130", "StreetNumberName", "petitioner.address_history[1].street"],
  ["I-130", "AptSteFlrNumber", "petitioner.address_history[1].unit_number"],
  ["I-130", "CityOrTown", "petitioner.address_history[1].city"],
  ["I-130", "State", "petitioner.address_history[1].state"],
  ["I-130", "ZipCode", "petitioner.address_history[1].zip"],
  ["I-130", "Province", "petitioner.address_history[1].province"],
  ["I-130", "PostalCode", "petitioner.address_history[1].postal_code"],
  ["I-130", "Country", "petitioner.address_history[1].country"],
  ["I-130", "DateFrom", "petitioner.address_history[1].date_from"],
  ["I-131", "FamilyName", "beneficiary.family_name"],
  ["I-131", "GivenName", "beneficiary.given_name"],
  ["I-131", "MiddleName", "beneficiary.middle_name"],
  ["I-131", "AlienNumber", "beneficiary.alien_number"],
  ["I-131", "CountryOfBirth", "beneficiary.country_of_birth"],
  ["I-131", "CountryOfCitizenshiporNationality", "beneficiary.country_of_citizenship"],
  ["I-131", "DateOfBirth", "beneficiary.date_of_birth"],
  ["I-131", "SSN", "beneficiary.ssn"],
  ["I-131", "USCISOnlineAcctNumber", "beneficiary.uscis_online_account_number"],
  ["I-131", "I94RecordNo", "beneficiary.i94_number"],
  ["I-485", "FamilyName", "beneficiary.family_name"],
  ["I-485", "GivenName", "beneficiary.given_name"],
  ["I-485", "MiddleName", "beneficiary.middle_name"],
  ["I-485", "DOB", "beneficiary.date_of_birth"],
  ["I-485", "AlienNumber", "beneficiary.alien_number"],
  ["I-485", "CB_Sex", "beneficiary.sex"],
  ["I-485", "CityTownOfBirth", "beneficiary.city_of_birth"],
  ["I-485", "CountryOfBirth", "beneficiary.country_of_birth"],
  ["I-485", "CountryofCitizenshipNationality", "beneficiary.country_of_citizenship"],
  ["I-485", "USCISAccountNumber", "beneficiary.uscis_online_account_number"],
  ["I-485", "SSN", "beneficiary.ssn"],
  ["I-485", "PassportNum", "beneficiary.passport_number"],
  ["I-485", "Passport", "beneficiary.passport_country"],
  ["I-485", "DateofArrival", "beneficiary.date_of_last_arrival"],
  ["I-485", "I94", "beneficiary.i94_number"],
  ["I-485", "Status", "beneficiary.status_at_last_arrival"],
  ["I-485", "Status", "beneficiary.current_immigration_status"],
  ["I-485", "CurrentStreetNumberName", "beneficiary.mailing_address.street"],
  ["I-485", "CurrentAptSteFlrNumber", "beneficiary.mailing_address.unit"],
  ["I-485", "CurrentCityOrTown", "beneficiary.mailing_address.city"],
  ["I-485", "CurrentState", "beneficiary.mailing_address.state"],
  ["I-485", "CurrentZipCode", "beneficiary.mailing_address.zip"],
  ["I-485", "MaritalStatus", "beneficiary.marital_status"],
  ["I-485", "DaytimePhoneNumber1", "beneficiary.daytime_phone"],
  ["I-485", "Email", "beneficiary.email"],
  ["I-485", "StreetNumberName", "beneficiary.address_history[1].street"],
  ["I-485", "S_AptSteFlrNumber", "beneficiary.address_history[1].unit_number"],
  ["I-485", "InCareOfName", "beneficiary.address_history[1].in_care_of"],
  ["I-485", "CityOrTown", "beneficiary.address_history[1].city"],
  ["I-485", "State", "beneficiary.address_history[1].state"],
  ["I-485", "ZipCode", "beneficiary.address_history[1].zip"],
  ["I-485", "Date", "beneficiary.address_history[1].date_from"],
  ["I-485", "PriorStreetName", "beneficiary.address_history[2].street"],
  ["I-485", "PriorAddress_Number", "beneficiary.address_history[2].unit_number"],
  ["I-485", "PriorInCareOfName", "beneficiary.address_history[2].in_care_of"],
  ["I-485", "PriorCity", "beneficiary.address_history[2].city"],
  ["I-485", "PriorState", "beneficiary.address_history[2].state"],
  ["I-485", "PriorZipCode", "beneficiary.address_history[2].zip"],
  ["I-485", "PriorProvince", "beneficiary.address_history[2].province"],
  ["I-485", "PriorPostalCode", "beneficiary.address_history[2].postal_code"],
  ["I-485", "PriorCountry", "beneficiary.address_history[2].country"],
  ["I-485", "PriorDateFrom", "beneficiary.address_history[2].date_from"],
  ["I-485", "riorDateTo", "beneficiary.address_history[2].date_to"],
  ["I-485", "YN", "immigration.applied_immigrant_visa_before"],
  ["I-485", "CityTown", "immigration.consulate_city"],
  ["I-485", "CityTownOfBirth", "immigration.consulate_country"],
  ["I-485", "Decision", "immigration.decision"],
  ["I-485", "Date", "immigration.decision_date"],
  ["I-485", "YN", "immigration.applied_for_residence_before"],
  ["I-485", "YN", "immigration.lpr_rescinded"],
  ["I-485", "EmployerName", "employment.history[1].employer_name"],
  ["I-485", "StreetName", "employment.history[1].street"],
  ["I-485", "Number", "employment.history[1].unit_number"],
  ["I-485", "City", "employment.history[1].city"],
  ["I-485", "State", "employment.history[1].state"],
  ["I-485", "ZipCode", "employment.history[1].zip"],
  ["I-485", "Province", "employment.history[1].province"],
  ["I-485", "PostalCode", "employment.history[1].postal_code"],
  ["I-485", "Country", "employment.history[1].country"],
  ["I-485", "DateFrom", "employment.history[1].date_from"],
  ["I-485", "DateTo", "employment.history[1].date_to"],
  ["I-485", "StreetName", "employment.history[1].support_source"],
  ["I-485", "EmployerName", "employment.history[2].employer_name"],
  ["I-485", "EmployerName", "employment.history[3].employer_name"],
  ["I-485", "FamilyName", "family.parents[1].family_name"],
  ["I-485", "GivenName", "family.parents[1].given_name"],
  ["I-485", "MiddleName", "family.parents[1].middle_name"],
  ["I-485", "FamilyName", "family.parents[1].birth_family_name"],
  ["I-485", "GivenName", "family.parents[1].birth_given_name"],
  ["I-485", "MiddleName", "family.parents[1].birth_middle_name"],
  ["I-485", "DateofBirth", "family.parents[1].date_of_birth"],
  ["I-485", "CityTownOfBirth", "family.parents[1].country_of_birth"],
  ["I-485", "FamilyName", "family.parents[2].family_name"],
  ["I-485", "GivenName", "family.parents[2].given_name"],
  ["I-485", "MiddleName", "family.parents[2].middle_name"],
  ["I-485", "FamilyName", "family.parents[2].birth_family_name"],
  ["I-485", "GivenName", "family.parents[2].birth_given_name"],
  ["I-485", "MiddleName", "family.parents[2].birth_middle_name"],
  ["I-485", "DateofBirth", "family.parents[2].date_of_birth"],
  ["I-485", "CityTownOfBirth", "family.parents[2].country_of_birth"],
  ["I-485", "TimesMarried", "marriage.times_married"],
  ["I-485", "FamilyName", "petitioner.family_name"],
  ["I-485", "GivenName", "petitioner.given_name"],
  ["I-485", "MiddleName", "petitioner.middle_name"],
  ["I-485", "AlienNumber", "petitioner.alien_number"],
  ["I-485", "Country", "petitioner.country_of_birth"],
  ["I-485", "DateofBirth", "petitioner.date_of_birth"],
  ["I-485", "StreetName", "petitioner.mailing_address.street"],
  ["I-485", "City", "petitioner.mailing_address.city"],
  ["I-485", "Province", "petitioner.mailing_address.province"],
  ["I-485", "PostalCode", "petitioner.mailing_address.postal_code"],
  ["I-485", "Country", "petitioner.mailing_address.country"],
  ["I-485", "DateofBirth", "marriage.date"],
  ["I-485", "CityTownOfBirth", "marriage.city"],
  ["I-485", "State", "marriage.state"],
  ["I-485", "Country", "marriage.country"],
  ["I-485", "FamilyName", "marriage.prior_spouses[1].family_name"],
  ["I-485", "GivenName", "marriage.prior_spouses[1].given_name"],
  ["I-485", "MiddleName", "marriage.prior_spouses[1].middle_name"],
  ["I-485", "DateofBirth", "marriage.prior_spouses[1].date_of_birth"],
  ["I-485", "Country", "marriage.prior_spouses[1].country_of_birth"],
  ["I-485", "Country", "marriage.prior_spouses[1].country_of_citizenship"],
  ["I-485", "DateofBirth", "marriage.prior_spouses[1].marriage_date"],
  ["I-485", "CityTownOfBirth", "marriage.prior_spouses[1].marriage_city"],
  ["I-485", "State", "marriage.prior_spouses[1].marriage_state"],
  ["I-485", "Country", "marriage.prior_spouses[1].marriage_country"],
  ["I-485", "DateofBirth", "marriage.prior_spouses[1].ended_date"],
  ["I-485", "CityTownOfBirth", "marriage.prior_spouses[1].ended_city"],
  ["I-485", "State", "marriage.prior_spouses[1].ended_state"],
  ["I-485", "Country", "marriage.prior_spouses[1].ended_country"],
  ["I-485", "MaritalStatus", "marriage.prior_spouses[1].how_ended"],
  ["I-485", "HowMarriageEndedOther", "marriage.prior_spouses[1].how_ended_other"],
  ["I-485", "FamilyName", "family.children[1].family_name"],
  ["I-485", "GivenName", "family.children[1].given_name"],
  ["I-485", "MiddleName", "family.children[1].middle_name"],
  ["I-485", "AlienNumber", "family.children[1].alien_number"],
  ["I-485", "DateofBirth", "family.children[1].date_of_birth"],
  ["I-485", "Country", "family.children[1].country_of_birth"],
  ["I-485", "Relationship", "family.children[1].relationship"],
  ["I-485", "YN", "family.children[1].applying_separately"],
  ["I-485", "FamilyName", "family.children[2].family_name"],
  ["I-485", "GivenName", "family.children[2].given_name"],
  ["I-485", "MiddleName", "family.children[2].middle_name"],
  ["I-485", "AlienNumber", "family.children[2].alien_number"],
  ["I-485", "DateofBirth", "family.children[2].date_of_birth"],
  ["I-485", "Country", "family.children[2].country_of_birth"],
  ["I-485", "Relationship", "family.children[2].relationship"],
  ["I-485", "YN", "family.children[2].applying_separately"],
  ["I-485", "Ethnicity", "biographic.ethnicity"],
  ["I-485", "Race", "biographic.race"],
  ["I-485", "HeightFeet", "biographic.height_feet"],
  ["I-485", "HeightInches", "biographic.height_inches"],
  ["I-485", "Eyecolor", "biographic.eye_color"],
  ["I-485", "Haircolor", "biographic.hair_color"],
  ["I-693", "FamilyName", "beneficiary.family_name"],
  ["I-693", "GivenName", "beneficiary.given_name"],
  ["I-693", "MiddleName", "beneficiary.middle_name"],
  ["I-693", "DateOfBirth", "beneficiary.date_of_birth"],
  ["I-693", "AlienNumber", "beneficiary.alien_number"],
  ["I-765", "FamilyName", "beneficiary.family_name"],
  ["I-765", "GivenName", "beneficiary.given_name"],
  ["I-765", "MiddleName", "beneficiary.middle_name"],
  ["I-765", "AlienNumber", "beneficiary.alien_number"],
  ["I-765", "ElisAccountNumber", "beneficiary.uscis_online_account_number"],
  ["I-765", "Checkbox", "beneficiary.sex"],
  ["I-765", "SSN", "beneficiary.ssn"],
  ["I-765", "CityTownOfBirth", "beneficiary.city_of_birth"],
  ["I-765", "DOB", "beneficiary.date_of_birth"],
  ["I-765", "DaytimePhoneNumber1", "beneficiary.daytime_phone"],
  ["I-765", "Email", "beneficiary.email"],
  ["I-864", "FamilyName", "petitioner.family_name"],
  ["I-864", "GivenName", "petitioner.given_name"],
  ["I-864", "MiddleName", "petitioner.middle_name"],
  ["I-864", "DateOfBirth", "petitioner.date_of_birth"],
  ["I-864", "SocialSecurityNumber", "petitioner.ssn"],
  ["I-864", "FamilyName", "beneficiary.family_name"],
  ["I-864", "GivenName", "beneficiary.given_name"],
  ["I-864", "MiddleName", "beneficiary.middle_name"],
  ["I-864", "CountryCitizenship", "beneficiary.country_of_citizenship"],
  ["I-864", "DateOfBirth", "beneficiary.date_of_birth"],
  ["I-864", "AlienNumber", "beneficiary.alien_number"],
  ["I-864", "USCISOnlineAcctNumber", "beneficiary.uscis_online_account_number"],
  ["I-864", "DaytimePhoneNumber", "beneficiary.daytime_phone"],
  ["I-864", "TotalIncome", "sponsor.annual_income"],
  ["I-864", "InCareOf", "petitioner.mailing_address.in_care_of"],
  ["I-864", "StreetNumberName", "petitioner.mailing_address.street"],
  ["I-864", "AptSteFlrNumber", "petitioner.mailing_address.unit"],
  ["I-864", "CityOrTown", "petitioner.mailing_address.city"],
  ["I-864", "State", "petitioner.mailing_address.state"],
  ["I-864", "ZipCode", "petitioner.mailing_address.zip"],
  ["I-864", "Province", "petitioner.mailing_address.province"],
  ["I-864", "PostalCode", "petitioner.mailing_address.postal_code"],
  ["I-864", "Country", "petitioner.mailing_address.country"],
  ["I-864", "StreetNumberName", "petitioner.address_history[1].street"],
  ["I-864", "AptSteFlrNumber", "petitioner.address_history[1].unit_number"],
  ["I-864", "CityOrTown", "petitioner.address_history[1].city"],
  ["I-864", "State", "petitioner.address_history[1].state"],
  ["I-864", "ZipCode", "petitioner.address_history[1].zip"],
  ["I-864", "Province", "petitioner.address_history[1].province"],
  ["I-864", "PostalCode", "petitioner.address_history[1].postal_code"],
  ["I-864", "Country", "petitioner.address_history[1].country"],
  ["I-864", "StreetNumberName", "beneficiary.mailing_address.street"],
  ["I-864", "AptSteFlrNumber", "beneficiary.mailing_address.unit"],
  ["I-864", "CityOrTown", "beneficiary.mailing_address.city"],
  ["I-864", "State", "beneficiary.mailing_address.state"],
  ["I-864", "ZipCode", "beneficiary.mailing_address.zip"],
  ["I-864", "TotalHouseholdIncome", "sponsor.household_income"],
  ["I-864", "Checkbox", "sponsor.filed_tax_returns"],
  ["I-864", "TaxYear", "sponsor.tax_returns[1].tax_year"],
  ["I-864", "TotalIncome", "sponsor.tax_returns[1].total_income"],
  ["I-864", "TaxYear", "sponsor.tax_returns[2].tax_year"],
  ["I-864", "TotalIncome", "sponsor.tax_returns[2].total_income"],
  ["I-864", "TaxYear", "sponsor.tax_returns[3].tax_year"],
  ["I-864", "TotalIncome", "sponsor.tax_returns[3].total_income"],
];

/** Every datum those mappings name — the list the picker searches. */
export const VOCABULARY: readonly string[] = [
  "beneficiary.address_history[1].city",
  "beneficiary.address_history[1].date_from",
  "beneficiary.address_history[1].in_care_of",
  "beneficiary.address_history[1].state",
  "beneficiary.address_history[1].street",
  "beneficiary.address_history[1].unit_number",
  "beneficiary.address_history[1].zip",
  "beneficiary.address_history[2].city",
  "beneficiary.address_history[2].country",
  "beneficiary.address_history[2].date_from",
  "beneficiary.address_history[2].date_to",
  "beneficiary.address_history[2].in_care_of",
  "beneficiary.address_history[2].postal_code",
  "beneficiary.address_history[2].province",
  "beneficiary.address_history[2].state",
  "beneficiary.address_history[2].street",
  "beneficiary.address_history[2].unit_number",
  "beneficiary.address_history[2].zip",
  "beneficiary.alien_number",
  "beneficiary.city_of_birth",
  "beneficiary.country_of_birth",
  "beneficiary.country_of_citizenship",
  "beneficiary.current_immigration_status",
  "beneficiary.date_of_birth",
  "beneficiary.date_of_last_arrival",
  "beneficiary.daytime_phone",
  "beneficiary.email",
  "beneficiary.family_name",
  "beneficiary.given_name",
  "beneficiary.i94_number",
  "beneficiary.mailing_address.city",
  "beneficiary.mailing_address.state",
  "beneficiary.mailing_address.street",
  "beneficiary.mailing_address.unit",
  "beneficiary.mailing_address.zip",
  "beneficiary.marital_status",
  "beneficiary.middle_name",
  "beneficiary.passport_country",
  "beneficiary.passport_number",
  "beneficiary.sex",
  "beneficiary.ssn",
  "beneficiary.status_at_last_arrival",
  "beneficiary.uscis_online_account_number",
  "biographic.ethnicity",
  "biographic.eye_color",
  "biographic.hair_color",
  "biographic.height_feet",
  "biographic.height_inches",
  "biographic.race",
  "employment.history[1].city",
  "employment.history[1].country",
  "employment.history[1].date_from",
  "employment.history[1].date_to",
  "employment.history[1].employer_name",
  "employment.history[1].postal_code",
  "employment.history[1].province",
  "employment.history[1].state",
  "employment.history[1].street",
  "employment.history[1].support_source",
  "employment.history[1].unit_number",
  "employment.history[1].zip",
  "employment.history[2].employer_name",
  "employment.history[3].employer_name",
  "family.children[1].alien_number",
  "family.children[1].applying_separately",
  "family.children[1].country_of_birth",
  "family.children[1].date_of_birth",
  "family.children[1].family_name",
  "family.children[1].given_name",
  "family.children[1].middle_name",
  "family.children[1].relationship",
  "family.children[2].alien_number",
  "family.children[2].applying_separately",
  "family.children[2].country_of_birth",
  "family.children[2].date_of_birth",
  "family.children[2].family_name",
  "family.children[2].given_name",
  "family.children[2].middle_name",
  "family.children[2].relationship",
  "family.parents[1].birth_family_name",
  "family.parents[1].birth_given_name",
  "family.parents[1].birth_middle_name",
  "family.parents[1].country_of_birth",
  "family.parents[1].date_of_birth",
  "family.parents[1].family_name",
  "family.parents[1].given_name",
  "family.parents[1].middle_name",
  "family.parents[2].birth_family_name",
  "family.parents[2].birth_given_name",
  "family.parents[2].birth_middle_name",
  "family.parents[2].country_of_birth",
  "family.parents[2].date_of_birth",
  "family.parents[2].family_name",
  "family.parents[2].given_name",
  "family.parents[2].middle_name",
  "immigration.applied_for_residence_before",
  "immigration.applied_immigrant_visa_before",
  "immigration.consulate_city",
  "immigration.consulate_country",
  "immigration.decision",
  "immigration.decision_date",
  "immigration.lpr_rescinded",
  "marriage.city",
  "marriage.country",
  "marriage.date",
  "marriage.prior_spouses[1].country_of_birth",
  "marriage.prior_spouses[1].country_of_citizenship",
  "marriage.prior_spouses[1].date_of_birth",
  "marriage.prior_spouses[1].ended_city",
  "marriage.prior_spouses[1].ended_country",
  "marriage.prior_spouses[1].ended_date",
  "marriage.prior_spouses[1].ended_state",
  "marriage.prior_spouses[1].family_name",
  "marriage.prior_spouses[1].given_name",
  "marriage.prior_spouses[1].how_ended",
  "marriage.prior_spouses[1].how_ended_other",
  "marriage.prior_spouses[1].marriage_city",
  "marriage.prior_spouses[1].marriage_country",
  "marriage.prior_spouses[1].marriage_date",
  "marriage.prior_spouses[1].marriage_state",
  "marriage.prior_spouses[1].middle_name",
  "marriage.state",
  "marriage.times_married",
  "petitioner.address_history[1].city",
  "petitioner.address_history[1].country",
  "petitioner.address_history[1].date_from",
  "petitioner.address_history[1].postal_code",
  "petitioner.address_history[1].province",
  "petitioner.address_history[1].state",
  "petitioner.address_history[1].street",
  "petitioner.address_history[1].unit_number",
  "petitioner.address_history[1].zip",
  "petitioner.alien_number",
  "petitioner.country_of_birth",
  "petitioner.date_of_birth",
  "petitioner.daytime_phone",
  "petitioner.email",
  "petitioner.family_name",
  "petitioner.given_name",
  "petitioner.mailing_address.city",
  "petitioner.mailing_address.country",
  "petitioner.mailing_address.in_care_of",
  "petitioner.mailing_address.postal_code",
  "petitioner.mailing_address.province",
  "petitioner.mailing_address.state",
  "petitioner.mailing_address.street",
  "petitioner.mailing_address.unit",
  "petitioner.mailing_address.zip",
  "petitioner.middle_name",
  "petitioner.ssn",
  "sponsor.annual_income",
  "sponsor.filed_tax_returns",
  "sponsor.household_income",
  "sponsor.tax_returns[1].tax_year",
  "sponsor.tax_returns[1].total_income",
  "sponsor.tax_returns[2].tax_year",
  "sponsor.tax_returns[2].total_income",
  "sponsor.tax_returns[3].tax_year",
  "sponsor.tax_returns[3].total_income",
];
