/* eslint-disable react-refresh/only-export-components */
import { parseAsString, useQueryState } from "nuqs";
import {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useState,
  type ReactNode,
} from "react";
import dayjs from "dayjs";
import { useCalendarEvents, useCreateCalendarEvent } from "./use-calendar";
import type {
  CalendarEvent,
  CalendarEventType,
  CalendarViewType,
  CreateCalendarEventRequest,
} from "./types";

interface CalendarDataContextValue {
  view: CalendarViewType;
  setView: (v: CalendarViewType) => void;
  currentDate: Date;
  setCurrentDate: (d: Date) => void;
  handlePrev: () => void;
  handleNext: () => void;
  handleToday: () => void;
  filter: CalendarEventType | undefined;
  events: CalendarEvent[];
  displayedEvents: CalendarEvent[];
  isLoading: boolean;
  isMobile: boolean;
  // Add event
  slotData: { start: Date; end: Date } | null;
  setSlotData: (s: { start: Date; end: Date } | null) => void;
  handleAddSubmit: (payload: CreateCalendarEventRequest) => void;
  // Detail dialog
  selectedEventId: string | null;
  openDetail: (id: string) => void;
  closeDetail: () => void;
}

const CalendarDataContext = createContext<CalendarDataContextValue | null>(null);

export function CalendarDataProvider({
  children,
  filter,
}: {
  children: ReactNode;
  filter?: CalendarEventType;
}) {
  const [view, setView] = useQueryState(
    "view",
    parseAsString.withDefault("month" as CalendarViewType),
  );
  const [dateStr, setDateStr] = useQueryState(
    "date",
    parseAsString.withDefault(""),
  );

  const [currentDate, setCurrentDateState] = useState<Date>(() => {
    if (dateStr) {
      const parsed = dayjs(dateStr);
      if (parsed.isValid()) return parsed.toDate();
    }
    return new Date();
  });

  const [slotData, setSlotData] = useState<{
    start: Date;
    end: Date;
  } | null>(null);
  const [selectedEventId, setSelectedEventId] = useState<string | null>(null);
  const [isMobile, setIsMobile] = useState(false);

  const year = currentDate.getFullYear();
  const month = currentDate.getMonth() + 1;

  const { data: rawEvents, isLoading } = useCalendarEvents(year, month);
  const createEvent = useCreateCalendarEvent();

  const events = useMemo(() => {
    if (!rawEvents) return [];
    return rawEvents.map((e) => ({
      id: e.id,
      title: e.title,
      start: new Date(e.startTime),
      end: e.endTime ? new Date(e.endTime) : new Date(e.startTime),
      type: e.eventType,
      status: e.status,
      caseId: e.case?.id ?? undefined,
      clientId: e.client?.id ?? undefined,
      clientName: e.client?.name ?? undefined,
      caseNumber: e.case?.caseNumber ?? undefined,
      assignedStaffId: e.assignedStaff?.id ?? undefined,
      assignedStaffName: e.assignedStaff?.name ?? undefined,
      assignedStaffRole: e.assignedStaff?.role ?? undefined,
      leadId: e.lead?.id ?? undefined,
      leadName: e.lead?.name ?? undefined,
      location: e.location ?? undefined,
      zoomLink: e.zoomLink ?? undefined,
      notes: e.notes ?? undefined,
      isAutoGenerated: e.isAutoGenerated,
      parentEventId: e.parentEventId ?? undefined,
    }));
  }, [rawEvents]);

  const displayedEvents = filter
    ? events.filter((e) => e.type === filter)
    : events;

  useEffect(() => {
    const check = () => setIsMobile(window.innerWidth < 768);
    check();
    window.addEventListener("resize", check);
    return () => window.removeEventListener("resize", check);
  }, []);

  const setCurrentDate = useCallback(
    (d: Date) => {
      setCurrentDateState(d);
      setDateStr(dayjs(d).format("YYYY-MM-DD"));
    },
    [setDateStr],
  );

  const handlePrev = useCallback(() => {
    setCurrentDateState((prev) => {
      const d = dayjs(prev);
      const next =
        view === "month"
          ? d.subtract(1, "month")
          : view === "week"
            ? d.subtract(1, "week")
            : d.subtract(1, "day");
      const nextDate = next.toDate();
      setDateStr(next.format("YYYY-MM-DD"));
      return nextDate;
    });
  }, [view, setDateStr]);

  const handleNext = useCallback(() => {
    setCurrentDateState((prev) => {
      const d = dayjs(prev);
      const next =
        view === "month"
          ? d.add(1, "month")
          : view === "week"
            ? d.add(1, "week")
            : d.add(1, "day");
      const nextDate = next.toDate();
      setDateStr(next.format("YYYY-MM-DD"));
      return nextDate;
    });
  }, [view, setDateStr]);

  const handleToday = useCallback(() => {
    const now = new Date();
    setCurrentDateState(now);
    setDateStr(dayjs(now).format("YYYY-MM-DD"));
  }, [setDateStr]);

  const handleAddSubmit = useCallback(
    (payload: CreateCalendarEventRequest) => {
      createEvent.mutate(payload);
    },
    [createEvent],
  );

  const openDetail = useCallback((id: string) => {
    setSelectedEventId(id);
  }, []);

  const closeDetail = useCallback(() => {
    setSelectedEventId(null);
  }, []);

  const value: CalendarDataContextValue = useMemo(
    () => ({
      view: view as CalendarViewType,
      setView: (v: CalendarViewType) => setView(v),
      currentDate,
      setCurrentDate,
      handlePrev,
      handleNext,
      handleToday,
      filter,
      events,
      displayedEvents,
      isLoading,
      isMobile,
      slotData,
      setSlotData,
      handleAddSubmit,
      selectedEventId,
      openDetail,
      closeDetail,
    }),
    [
      view,
      setView,
      currentDate,
      setCurrentDate,
      handlePrev,
      handleNext,
      handleToday,
      filter,
      events,
      displayedEvents,
      isLoading,
      isMobile,
      slotData,
      setSlotData,
      handleAddSubmit,
      selectedEventId,
      openDetail,
      closeDetail,
    ],
  );

  return (
    <CalendarDataContext.Provider value={value}>
      {children}
    </CalendarDataContext.Provider>
  );
}

export function useCalendarData() {
  const ctx = useContext(CalendarDataContext);
  if (!ctx)
    throw new Error(
      "useCalendarData must be used within CalendarDataProvider",
    );
  return ctx;
}
