export type CalendarViewType = "month" | "week" | "day";

export type CalendarEventType =
  | "master_calendar_hearing"
  | "individual_hearing"
  | "uscis_interview"
  | "biometric"
  | "filing_deadline"
  | "service_request"
  | "client_meeting"
  | "internal_event";

export type CalendarEventStatus = "scheduled" | "completed" | "cancelled";

export interface CalendarEvent {
  id: string;
  title: string;
  start: Date;
  end: Date;
  type: CalendarEventType;
  status: CalendarEventStatus;
  caseId?: string;
  clientId?: string;
  clientName?: string;
  caseNumber?: string;
  assignedStaffId?: string;
  assignedStaffName?: string;
  assignedStaffRole?: string;
  leadId?: string;
  leadName?: string;
  location?: string;
  zoomLink?: string;
  notes?: string;
  isAutoGenerated?: boolean;
  parentEventId?: string;
}

export interface CalendarEventResponse {
  id: string;
  eventType: CalendarEventType;
  status: CalendarEventStatus;
  title: string;
  startTime: string;
  endTime: string | null;
  location: string | null;
  zoomLink: string | null;
  notes: string | null;
  isAutoGenerated: boolean;
  parentEventId: string | null;
  teamId: string | null;
  client: { id: string; name: string } | null;
  case: { id: string; caseNumber: string } | null;
  assignedStaff: { id: string; name: string; role: string } | null;
  lead: { id: string; name: string } | null;
}

export interface CalendarEventDetailResponse extends CalendarEventResponse {
  autoGeneratedDeadlines: CalendarEventResponse[];
}

export interface UpdateCalendarEventRequest {
  status?: CalendarEventStatus;
  title?: string;
  eventType?: CalendarEventType;
  startTime?: string;
  endTime?: string;
  location?: string;
  zoomLink?: string;
  notes?: string;
  assignedStaffId?: string;
  clientId?: string;
  caseId?: string;
}

export interface CreateCalendarEventRequest {
  title: string;
  eventType: CalendarEventType;
  startTime: string;
  endTime?: string;
  caseId?: string;
  clientId?: string;
  leadId?: string;
  assignedStaffId?: string;
  location?: string;
  zoomLink?: string;
  notes?: string;
}

export interface CalendarStripDay {
  date: string;
  hearings: number;
  uscisInterviews: number;
  biometrics: number;
  other: number;
  total: number;
}

export interface CreateServiceRequestEventRequest {
  clientId: string;
  caseId: string;
  clientName: string;
  formType: string;
  assignedStaffId?: string;
  teamId?: string;
}

export const EVENT_TYPE_CONFIG: Record<
  CalendarEventType,
  { color: string; label: string; bgAlpha: string }
> = {
  master_calendar_hearing: {
    color: "#EF4444",
    label: "Master calendar hearing",
    bgAlpha: "#EF444420",
  },
  individual_hearing: {
    color: "#F97316",
    label: "Individual hearing",
    bgAlpha: "#F9731620",
  },
  uscis_interview: {
    color: "#3B82F6",
    label: "USCIS interview",
    bgAlpha: "#3B82F620",
  },
  biometric: {
    color: "#06B6D4",
    label: "Biometric appointment",
    bgAlpha: "#06B6D420",
  },
  filing_deadline: {
    color: "#D97706",
    label: "Filing deadline",
    bgAlpha: "#D9770620",
  },
  service_request: {
    color: "#8B5CF6",
    label: "Service request",
    bgAlpha: "#8B5CF620",
  },
  client_meeting: {
    color: "#22C55E",
    label: "Client meeting",
    bgAlpha: "#22C55E20",
  },
  internal_event: {
    color: "#93C5FD",
    label: "Internal / staff event",
    bgAlpha: "#93C5FD20",
  },
};

export const CALENDAR_FILTER_TYPES: CalendarEventType[] = [
  "master_calendar_hearing",
  "individual_hearing",
  "uscis_interview",
  "biometric",
  "filing_deadline",
  "service_request",
  "client_meeting",
  "internal_event",
];
