import { AlertTriangle, FileText, PenLine } from "lucide-react";
import { feeAgreements } from "../data";

export function FeeAgreementView() {
  return (
    <section className="fee-agreement-section" aria-label="Fee agreements">
      <header className="questionnaire-toolbar">
        <p>1 fee agreement pending signature</p>
        <button className="secondary-button" type="button">
          <FileText size={14} />
          Generate agreement
        </button>
      </header>

      <div className="fee-agreement-list">
        {feeAgreements.map((agreement) => (
          <article
            key={agreement.title}
            className="surface-card work-card fee-agreement-card"
          >
            <header className="work-card__header">
              <div>
                <h2 className="work-card__title">{agreement.title}</h2>
                <div className="work-card__meta fee-agreement-card__meta">
                  <span className={`practice-pill practice-pill--${agreement.practiceTone}`}>
                    {agreement.practiceArea}
                  </span>
                  <span>Generated by {agreement.generatedBy}</span>
                </div>
                {!agreement.addOnActive ? (
                  <span className="lead-add-on-warning fee-agreement-card__warning">
                    <AlertTriangle size={11} />
                    Not active
                  </span>
                ) : null}
              </div>
              <span className="document-status document-status--pending fee-agreement-status">
                <PenLine size={11} />
                {agreement.statusLabel}
              </span>
            </header>

            <div className="fee-progress">
              <div className="fee-progress__copy">
                <span>Awaiting client digital signature</span>
                <span>{agreement.progressLabel}</span>
              </div>
              <span className="fee-progress__track">
                <span
                  className="fee-progress__fill"
                  style={{ width: `${agreement.progress}%` }}
                />
              </span>
            </div>

            <div className="work-card__actions fee-agreement-card__actions">
              <button className="secondary-button fee-agreement-card__button" type="button">
                Nudge client
              </button>
              <button className="brand-button fee-agreement-card__button" type="button">
                <PenLine size={14} />
                Advance stage (Digital Sign)
              </button>
            </div>
          </article>
        ))}
      </div>
    </section>
  );
}
