import { Box, HStack, Stack } from "@chakra-ui/react";
import { AlertTriangle, FileText, PenLine } from "lucide-react";
import { feeAgreements } from "../data";
import {
  BrandButton,
  CardTitle,
  MutedText,
  OutlineButton,
  PracticePill,
  StatusPill,
  SurfaceCard,
} from "./intake-ui";

export function FeeAgreementView() {
  return (
    <Stack gap="16px" pt="24px" aria-label="Fee agreements">
      <HStack justify="space-between" gap="16px" wrap="wrap">
        <MutedText fontSize="14px">1 fee agreement pending signature</MutedText>
        <OutlineButton>
          <FileText size={14} />
          Generate agreement
        </OutlineButton>
      </HStack>

      <Stack gap="14px">
        {feeAgreements.map((agreement) => (
          <SurfaceCard key={agreement.title}>
            <HStack align="flex-start" justify="space-between" gap="16px">
              <Box>
                <CardTitle>{agreement.title}</CardTitle>
                <HStack mt="6px" gap="9px">
                  <PracticePill tone={agreement.practiceTone}>
                    {agreement.practiceArea}
                  </PracticePill>
                  <MutedText>Generated by {agreement.generatedBy}</MutedText>
                </HStack>
                {!agreement.addOnActive ? (
                  <HStack mt="0" gap="3px" color="brand.700" fontSize="10px" fontWeight="500">
                    <AlertTriangle size={11} />
                    <Box as="span">Not active</Box>
                  </HStack>
                ) : null}
              </Box>
              <StatusPill tone="warning" icon={<PenLine size={11} />}>
                {agreement.statusLabel}
              </StatusPill>
            </HStack>

            <Stack
              gap="8px"
              mt="26px"
              pb="24px"
              borderBottom="1px solid"
              borderColor="border.subtle"
            >
              <HStack justify="space-between" gap="16px" color="fg.muted" fontSize="12px">
                <Box as="span">Awaiting client digital signature</Box>
                <Box as="span">{agreement.progressLabel}</Box>
              </HStack>
              <Box w="100%" h="6px" borderRadius="999px" bg="bg.subtle" overflow="hidden">
                <Box
                  h="100%"
                  borderRadius="inherit"
                  bg="brand.solid"
                  style={{ width: `${agreement.progress}%` }}
                />
              </Box>
            </Stack>

            <Box
              display="grid"
              gridTemplateColumns={{ base: "1fr", md: "1fr 1fr" }}
              gap="8px"
              mt="14px"
            >
              <OutlineButton>Nudge client</OutlineButton>
              <BrandButton>
                <PenLine size={14} />
                Advance stage (Digital Sign)
              </BrandButton>
            </Box>
          </SurfaceCard>
        ))}
      </Stack>
    </Stack>
  );
}
